### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fkr** [VeselaHouba/ansible-role-zammad#5]
Was wondering under which license this role is published - I like it and want to make sure, the license fits my use case before proceeding ;)

**Comment by VeselaHouba** [comment]
Didn't think about it yet to be honest. Quick answer: license must not conflict with Zammad's own license. And my own part would be: feel free to use redistiribute and modify as needed, I don't take any responsibility of any damage done. 

All PRs and issues are most welcome. I will check for proper formulation after holidays.

@fkr if you have any specific license in mind which fits your needs please let me know

**Comment by fkr** [comment]
@VeselaHouba thanks for the quick response. I'll stay tuned then. Any of the usual suspects (BSD, MIT, GPLv2/v3, Apache) is probably suited well.

**Comment by VeselaHouba** [comment]
Added license from Zammad's github project (copy-paste)
